FROM jupyter/base-notebook:python-3.10

RUN pip install numpy pandas matplotlib

COPY ../exercises/introduction.ipynb /home/jovyan/
COPY ../exercises/starter_challenges.ipynb /home/jovyan/
COPY ../exercises/turtle_exercise.ipynb /home/jovyan/
COPY ../exercises/temperature_sensor.ipynb /home/jovyan/
